### ISSUE TITLE
Error ECONNREFUSED can't ping

### ISSUE THREAD

**Issue by Tradmis** [ARCAD-Software/elias-vscode#14]
Hello team, 

I have an issue since few days, i am not able to connect to **ARCAD Elias** anymore on **VScode**.

### When i try to connect on ARCAD i have this error below : 

```
Error: connect ECONNREFUSED XXX.XXX.XX.XX:00000 
Can't ping http://SystemName:XXXXX/elias/arcad/v1
Error: connect ECONNREFUSED XXX.XXX.XX.XX:00000 
```

But i have changed nothing in my parameters and i don't use the "HTTPS" Rest Api Server, i am juste not able to connect on ARCAD Elias...

Can you help me to solve this problem please ? 

Thanks a lot for your job and if you have any question i still there !

Best regards,

**Comment by sebjulliand** [comment]
Hello,
this is most likely due to the Elias REST API server not running on your target system.

You an try to access this URL that requires no authentication from your browser to see if it's running: http://url:port/elias/arcad/v1/ping.

But I'd be surprised it's running given the error message you have.
So, your parameters are fine, your REST API server is not (anymore).
Get in touch with whoever is responsible for running the server and ask them to start or restart it.

**Comment by Tradmis** [comment]
Thank you very much the problem is solved !

Indeed you've been right, the REST API Elias service needed to be start because the server was shutting down this week-end and the service wasn't restart..

Best regards,
