### ISSUE TITLE
reposition into application explorer after compile

### ISSUE THREAD

**Issue by dev-wouter** [ARCAD-Software/elias-vscode#28]
Seb,

i like working with the favorites versions tab sub menu. but when i compile a source in a version in that i added in the favorite list, it jumps to one of the other menu's where the version is living.

![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/8529b413-0ba5-4375-b59d-c0c7a1635d3f)
for example
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/030328a1-9420-45bc-9a4f-5bdf4bc188f3)
i'm working in FT.23.03 and compile a source.
if the compilation is done it jumps to 'integrated versions' and that same feature.  (could be that it jumps to 'open versions' also)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/136235433/a835418a-b52d-420e-8cc6-ee84cc590521)

if i'm not mistaking a few versions ago this was not the behavior. 
working with 2.1.4

thanks for looking in to the 'issue'

**Comment by sebjulliand** [comment]
Hi,
actually, fixing https://github.com/ARCAD-Software/elias-vscode/issues/25 restored the "focus grabbing" functionality on every node that supports it. Since favorite version node and normal version nodes are the same, they both try to reveal the component when it gets compiled. Grabbing the focus is done by both nodes and the last one to reveal the component "wins".

Since it's an event based feature, the nodes don't know where the component was compiled from (can even be from the command palette for that mater).

But grabbing the focus is probably a bit too much for a compiled component. I'll simply disable the focus grab and it should be fine.

**Comment by sebjulliand** [comment]
@dev-wouter , here is a snapshot with the fix mentioned above. Let me know if that works for you:
[arcad-elias-2.1.5-SNAPSHOT.vsix.zip](https://github.com/user-attachments/files/16140909/arcad-elias-2.1.5-SNAPSHOT.vsix.zip)

With this, `Changed Components` nodes will only refresh themselves and not grab the focus.

**Comment by dev-wouter** [comment]
tested it, 

now the focus is not on a source or object but on the window 'Application explorer' 
witch is fine for me, there is no scrolling back to the 'Favorite versions' anymore. 

icon colors still update correctly. 

Thanks

**Comment by sebjulliand** [comment]
Perfect, thanks for your feedback!

**Comment by sebjulliand** [comment]
Fixed in version `2.1.5`.
