### ISSUE TITLE
History of component sometimes fails with error message

### ISSUE THREAD

**Issue by petterjohansson** [ARCAD-Software/elias-vscode#4]
![image](https://github.com/ARCAD-Software/elias-vscode/assets/12429224/f3548df4-2341-474c-b132-70e6ccd2e162)

**Comment by sebjulliand** [comment]
Turn on the Elias Traces in VSCode preferences, and try again. Then copy/paste the content of the Elias output.
Also, send over the relevant log file of the day, found under the logs folder of your Elias rest api server installation folder.

**Comment by sebjulliand** [comment]
@petterjohansson since this is most likely a server side issue (i.e. Elias REST server), I'll need you to do the following:
- Stop Jetty
- Open the `start.d/server.ini` file
- Add the following line under the existing modules list: `--module=logging-log4j2`
- Clear the `logs` folder (clear it, don't delete it)
- Restart Jetty

Then in VSCode, turn on the traces for Elias.
Reproduce the issue and then send here the Elias output content + the xxxx_yy_zz.jetty.log file from Jetty's logs folder (it should contain the Java trace of the HTTP 500 error).

Thanks

**Comment by mlstoppa** [comment]
Hi, I do experience the same error.
I'll try to restart the server, then in case the error appears again I will do as asked for.
Lucia

**Comment by sebjulliand** [comment]
Hi, no unfortunately I didn't have time to look at this more in depth.
But at least I can see that the XRef analysis had an issue, and it's related to a process that tries to compute a line number out of a member sequence number. Is `JAVAFTP` a component or something else that appears in your `NXTPRC03` component?

**Comment by mlstoppa** [comment]
JAVAFTP is prototyped as an external program:
`Dcl-Pr sendFileFTP ExtPgm('JAVAFTP');`

**Comment by sebjulliand** [comment]
Hi Lucia, sure thing. Sorry about the delay, it's been quite busy around here!
So, after giving a fresh look to this, the issue is due to the XRef analysis crashing while trying to compute a line number out of a sequence for a procedure call. For instance, it could not find `JAVAFTP`'s source member. That's what I can assume from this error message: `JAVAFTP in *N type *MEM not found.`

To carry on with the investigation, could you send me a screenshot of each of these 3 tabs, when opening the XRefs (i. e. the Open in ARCAD Observer action) for the NXTPRC03 program:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/7e442f57-2ac6-44c2-8d07-4bf8fd63384c)

Also, can you send me the calling chain displayed on 5250 for this component? Running `ADSPXRF REFTYPE('*PGMPGM') REFOBJ(NXTPRC03) TYPE('SQLRPGLE') APP('?') VERSLVL('?') USEAPPLNK('*USE') GENSTEP('*ALL')` should do the trick (I'll let you fill in the `APP` and `VERSLVL` parameters). Take a screenshot. Then press F11 to display the libraries and take another screenshot.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11096890/b590911b-9aaf-49d0-9f67-05bc212e87d4)

That may help determining why it cannot find that programs' source.
If that fails, I'll make the process not return anything for this procedure call when this issue happens.

**Comment by petterjohansson** [comment]
Hi
I should add to the conversation that I have not been able to reproduce the error since reporting it. :)
Petter

**Comment by mlstoppa** [comment]
Hi Sebastien, here I am. Sorry for the delay.
That's what you asked for:
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/f3322aec-7eb8-47ef-bf47-cbb351016481)
At this point the version has been moved to test.
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/496169e2-5391-4ce0-bb6e-3e18e1d4f26b)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/7628666b-4dfc-4b5b-9445-f14a4b0b6256)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/7e639fd7-f2fb-4290-9246-be2836b664d2)
![image](https://github.com/ARCAD-Software/elias-vscode/assets/11289821/0f6cfd01-5f8a-46f3-a785-b8c9ddb2db08)
Can I ask what you can derive from this list?
Thank you
Lucia

**Comment by mlstoppa** [comment]
Hi Sébastien,
It looks like sometimes it still happens even with the latest version, but so far I haven't been able to reproduce the case.
Do you mind keeping the issue open for a while?
Thank you
Lucia

**Comment by sebjulliand** [comment]
No worries, we'll keep it open.
Let me know whenever it can be reproduced. Thanks!

**Comment by mlstoppa** [comment]
To me, this issue can be closed. 
I'll keep you posted whenever it happens again and under what conditions.
Thank you!

**Comment by sebjulliand** [comment]
Excellent! Thank you!
