### ISSUE TITLE
ARCAD-Observer cross reference failed

### ISSUE THREAD

**Issue by sebCIL** [ARCAD-Software/elias-vscode#44]
Hi,

after an update, i have the message "ARCAD-Observer cross reference computation failed":

```
[04/10/2024 07:52:06] [ERR] {"status":500,"message":"Fatal error: java.lang.NullPointerException","data":"com.arcadsoftware.elias.rest.server.arcad.resource.XRefAnalyzisResource.resolveReference(XRefAnalyzisResource.java:219); com.arcadsoftware.elias.rest.server.arcad.resource.XRefAnalyzisResource.addImportedProcedure(XRefAnalyzisResource.java:160); com.arcadsoftware.elias.rest.server.arcad.resource.XRefAnalyzisResource.analyzeXref(XRefAnalyzisResource.java:124); sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method); sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)"}
``` 

I don't know how to have more details for this message.

I install the last version for the server & VSCode plug-in (2.2.0).

Thanks.

**Comment by sebjulliand** [comment]
Hi, there is enough details with this, at least for me to dig 😉
That happens when Elias tries to compute the cross references to display code lenses in the source code you're displaying. Seems like the process fails to resolve the library or the source file of an imported procedure.

Here's what I'd need to check:
- Right click in n the component for which this error occurs and select `Open in ARCAD-Observer`
- Go to the `Procedures` tab and send a screenshot of it
- On the IBM i, in Jetty's log folder, there should be an elias.log file. Attach it here as well.

Thanks!

**Comment by sebCIL** [comment]
This is obviously a configuration problem with the application...

There is a lot of procedures :
![image](https://github.com/user-attachments/assets/591f90ed-06a5-45b5-b3bf-1056b1f91831)

The log file:
[elias.log](https://github.com/user-attachments/files/17254721/elias.log)

I can see this message : `[MSG0475] [30] Objet/membre AUTVERIF, type SQLRPGLE inexistant ou n'appartient pas à l'appli DENITRAL.`
I don't know why it doesn't find the source file because is in the ROUTINEREF bib and the application add the library in the lib list:
![image](https://github.com/user-attachments/assets/8162f666-7637-4c95-ae75-1a68e5c86aa9)
and i check that the source exist:
![image](https://github.com/user-attachments/assets/cae54e90-06a2-4c00-bc6d-35387c100b49)

In RDI, i don't have this message but, perhaps, it was hidden. How can i check that in RDi there is the same problem or not ?

Tell me if i need to check configuration with my ARCAD contact.

**Comment by sebjulliand** [comment]
Or the problem may be that the process tries to resolve `AUTVERIF` as a component of the `DENITRAL` application whereas it's a component from another application!

Does `AUTVERIF` belongs to `DENITRAL` or does it come from another application?

**Comment by sebCIL** [comment]
Another application called ROUTINES

**Comment by sebjulliand** [comment]
Ok so thats the main issue. I'll fix it and upload a pre-release for you to validate it. Stay tuned!

**Comment by sebCIL** [comment]
Thank you for being so quick ! :+1:

**Comment by sebjulliand** [comment]
@sebCIL I created a pre-release to host the fix: https://github.com/ARCAD-Software/elias-vscode/releases/tag/2.2.1
Both the war (clear your jetty's work folder before restarting it) and the vsix need to be updated. The issue was linked to the way the cross-application references were retrieved (and the bug impacted a few other places).

Let me know how it goes and I'll make a release later on. Thanks!

**Comment by sebCIL** [comment]
Sounds googd:
![image](https://github.com/user-attachments/assets/3a01e1ac-13cf-44e0-860c-56ebc0f0f5e4)

No error message.
