### ISSUE TITLE
New source member added without description

### ISSUE THREAD

**Issue by mlstoppa** [ARCAD-Software/elias-vscode#6]
Hi!
I am trying the extension and faced this problem: when adding a new component I was asked to insert a name (W_TSTDTE), a description ('Test source date'), a type (RPGLE), and a functional tree option ('COMMON'). I inserted all the pieces of information required, but after reloading the Arcad-Skipper pane the new component displays the chosen function from the functional tree, but not the member description.
Attached you'll find the Elias server trace log, of which I deleted any non-relevant parts.
I made this test a few times, even creating a new version for this purpose, but the tests were all unsuccessful.
Also, from a 5250 session point of view, the result is the same: the member doesn't have a description.
Any hints?
Thank you
[Add_member_without_description.log](https://github.com/ARCAD-Software/elias-vscode/files/12514704/Add_member_without_description.log)

**Comment by sebjulliand** [comment]
Hi @mlstoppa !
The Component description is indeed not updated in ARCAD's database after its creation in VSCode. That part of the operation is missing.
However, since this requires a change in both the extension and the Rest API server, I won't be able to release it as a quick fix. This will be part of the next major update of Elias.
I'll let you know when it's available.

**Comment by mlstoppa** [comment]
Hi Sebastien,
That's fine, no worry. Knowing it's a future to come it's enough.
Thank you
Lucia
